version: ">= 1.12.2"

formatter: markdown table

sections:
  show:
    - header
    - inputs
    - providers
    - modules
    - footer

content: |-
  Any arbitrary text can be placed anywhere in the content

  {{ .Header }}

  and even in between sections. also spaces will be preserved:

  - item 1
    - item 1-1
    - item 1-2
  - item 2
  - item 3

  ## Resources
  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}

  ## Examples

  ```hcl
  {{ include "relative/path/to/main.tf" }}
  ```

  {{ .Providers }}

  and they don't even need to be in the default order

  {{ .Outputs }}

  {{ .Inputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    The template can be customized with aribitrary markdown content.
    For example this can be shown before the actual content generated
    by formatters.

    {{ .Content }}

    You can also show something after it!
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  indent: 4
  escape: false
  default: false
  required: false
  type: true
