name: "[CI] Teraform Share Document"

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.4.0

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint-cli2
        run: markdownlint-cli2 "default.md" "#node_modules"
